Updated books and book detail pages
eradovanovic/bookreview_project_front pull request #6
Opened 2022-08-15 13:25 UTC by eradovanovic

2022-08-17 09:01 UTC, Saraaaaaaaaaaaaaaa commented on src/components/Book/Book.js
> +                        {genres.map((genre) => <Chip key={genre} size="small" sx={{marginRight: '5px'}} label={genre} variant="outlined" /> )}
Oko genre ti ne trezaju zagrade, jer imas samo jedan, znaci samo ovako: genre => <Chip ... />
Takodje, za key je pametnije da stavis ako imas neki id, pa da bude genre.id

2022-08-17 09:03 UTC, Saraaaaaaaaaaaaaaa commented on src/components/Review/Review.js
> +const Review = (props) => {
Hajde ovde u zagradama da pisemo props. To bi izgledalo ovako: ({ prop1, prop2, prop3,... })

2022-08-17 09:04 UTC, Saraaaaaaaaaaaaaaa commented on src/components/Review/Review.js
> +
Da li mozes da dodas PropTypes? Generalno se to radi za svaku komponentu koja prima props.

2022-08-17 09:12 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/BookDetails/BookDetails.js
>          if(id != null){
id !== null

2022-08-17 09:15 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/BookDetails/BookDetails.js
> +import {getReviews} from "api/api";
Bolje je da uvek importujemo api, znaci da izgleda import api from 'api', a da su f-je u api.js-u const bez export const, cisto da bi izlgedalo lepse ako kasnije bude vise poziva na jednom screen-u ili komponenti.

2022-08-17 09:16 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/BookDetails/BookDetails.js
> +            getReviews(id).then(res =>
Onda bi ovde bilo api.getReviews(id)... i odmah bi bilo jasno sta je getReview

2022-08-17 09:26 UTC, Saraaaaaaaaaaaaaaa requested changes

2022-08-17 09:26 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/BookDetails/BookDetails.js
> +                            {genres.map((genre) => <Chip key={genre} size="small" sx={{marginRight: '5px', alignContent:'bottom'}} label={genre} variant="outlined" /> )}
Isti komentari za ovo kao i gore

2022-08-17 09:26 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/Books/Books.js
> +                            <FormControl sx={{width: '100%', margin: '10px'}}>
Ja bih celo ovo sortiranje izdvojila u posebnu komponentu, mozda bude potrebno i na nekom drugom mestu, a ima dosta koda

2022-08-17 09:26 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/Books/Books.js
> +                                    {names.map((name) => (
name bez zagrada

2022-08-17 09:26 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/Books/Books.js
> +                                        <MenuItem key={name} value={name}>
name.id ako ima za key

2022-08-17 09:26 UTC, Saraaaaaaaaaaaaaaa commented on src/pages/Books/Books.js
> +                    {books.map((book) => (
book bez zagrada

2022-08-18 08:41 UTC, Saraaaaaaaaaaaaaaa requested changes

2022-08-18 08:41 UTC, Saraaaaaaaaaaaaaaa commented on src/api/api.js
> +const api = {
Ovde moze samo ovako export default {
    getAuthorById,
    getBookById,
    getBooks,
    getReviews
}

2022-08-18 08:41 UTC, Saraaaaaaaaaaaaaaa commented on src/components/Book/Book.js
> +        genres: PropTypes.array,
Ovde nam ovako nesto treba:
      genred: PropTypes.arrayOf(PropTypes.shape({
        id: PropTypes.number,
        name: PropTypes.string,
      }))
      Moramo da ispisemo i za nizove i za objekte tipove. Takodje, ako je neki od njih obaveza prop, treba dodati .isRequired

2022-08-18 08:41 UTC, Saraaaaaaaaaaaaaaa commented on src/store/authors/authorsActions.js
>  export const fetchAuthorSuccess = (data) => ({
Ovde ti isto ne trebaju zagrade oko data. Uvek kada imas jedan parametar, zagrade ti ne trebaju

2022-08-24 07:38 UTC, anyamiletic commented on src/pages/BookDetails/BookDetails.js
>          if(id != null){
uvek radimo sa `===` ili `!==`, jer `== / !=` rade konverziju tipova - sto dovodi do cestih bagova. Proveri da li, ako ne prosledis id u parametrima, varijabla id bude `null` ili `undefined`, jer ako je npr `undefined` onda `id !== null -> true` za `id = undefined`

2022-08-24 08:36 UTC, Saraaaaaaaaaaaaaaa approved these changes

2022-08-24 09:20 UTC, anyamiletic commented on src/pages/Books/Books.js
>          } = event;
both of these are using `event.target.value` but are inconsistent in implementation. So either put something like this `genresHandler = ({ target: { value } })` for both, or in the place you are using the handler, put `onChange={e => genresHandler(e.target.value)}`

2022-08-24 09:20 UTC, anyamiletic commented on src/pages/Books/Books.js
>  import {BOOKS_PER_PAGE, SORT} from "constants";
```suggestion
import {BOOKS_PER_PAGE, SORT} from "/constants";
```

if you import something without `/` at the beginning of the path, the compiler thinks it is a node module, not a custom directory

2022-08-28 15:26 UTC, anyamiletic approved these changes

2022-08-31 08:28 UTC, merged